#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "zeronet"
name = "ZeroNet"
description.en = "Decentralized websites using Bitcoin crypto and BitTorrent network"
description.fr = "Sites Web décentralisés utilisant la crypto Bitcoin et le réseau BitTorrent"

version = "2021.01.25~ynh2"

maintainers = ["whypsi"]

[upstream]
license = "AGPL-3.0"
website = "https://zeronet.io"
admindoc = "https://zeronet.io/docs/"
code = "https://github.com/HelloZeroNet/ZeroNet"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "200M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.password]
    type = "password"
    optional = true

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/HelloZeroNet/ZeroNet/archive/454c0b2e7e000fda7000cba49027541fbf327b96.tar.gz"
    sha256 = "9286971422470cedb8ca5f6675863816bf3f05f0769842a1bdc12f85fc594938"
    autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["data", "log"]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 43110
    fs.default = 15441
    fs.exposed = "TCP"

    [resources.apt]
    packages = [
        "python3-venv",
        "python3-pip"
    ]
