#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1

[default]

    args.password = "secret123"

    [default.test_upgrade_from.628e89b0536a3c1ff7e5f9d903527b670690b336]
    name = "0.7.1~ynh1"
    args.password = "secret123"
